[package]
name = "flight-alert"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
scraper = "0.13"
fantoccini = "0.17"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"